### ISSUE TITLE
White text on white background

### ISSUE THREAD

**Issue by alberto2000** [sindresorhus/hyper-snazzy#12]
I don't know if this is an issue with Pure or with Snazzy:

![Screenshot](https://i.imgsafe.org/b7859cf4e2.png)

There are situations where white text is put on white background. I'm using Hyperterm, Zsh shell, Oh My Zsh, Pure and Snazzy. Any idea on this?

**Comment by zeke** [comment]
Same setup here, minus the oh-my-zsh, and I'm also seeing white on white. This is an example of [pick](https://robots.thoughtbot.com/announcing-pick):

![screen shot 2016-11-15 at 1 26 07 pm](https://cloud.githubusercontent.com/assets/2289/20324880/21edd5be-ab37-11e6-958c-fcb98b0a3681.png)

**Comment by alberto2000** [comment]
@zeke just found this is an issue with Hyper actually https://github.com/zeit/hyper/issues/883

**Comment by zeke** [comment]
Thanks, @alberto2000. However, the `span {background-color: transparent !important;}` hack actually made the selection "bar" invisible for me, which is actually worse than it blocking out the selected item.

**Comment by sindresorhus** [comment]
Yup, will be fixed in the next release of Hyper: https://github.com/zeit/hyper/commit/48dd4b5c1f2496be5b2ba19be1310ec2b2a85506

**Comment by alberto2000** [comment]
@sindresorhus this is still happening in 0.8.3.873
