### ISSUE TITLE
Request: Vim theme

### ISSUE THREAD

**Issue by benoror** [sindresorhus/hyper-snazzy#13]

**Comment by Jarvvski** [comment]
I've got a semi port of the scheme into vim. If @sindresorhus is happy for me to, I will link it here

**Comment by montlebalm** [comment]
@Jarvvski I'd be interested in seeing a Vim port or an existing theme that compliments Snazzy.

**Comment by Jarvvski** [comment]
@montlebalm I just have vim use the cterm values, so:

```
hi javaRepeat ctermfg = green
hi javaType ctermfg = green
hi javaStorageClass ctermfg = green cterm=bold
hi javaDocTags ctermfg = green
hi Conditional ctermfg = green
hi LineNr ctermfg = magenta
hi Comment ctermfg = red
hi Statement ctermfg = blue
hi Function ctermfg = blue
hi Identifier ctermfg = blue
hi Exception ctermfg = green
hi Special ctermfg = green
hi String ctermfg = yellow
hi MatchParen ctermbg=none cterm=underline ctermfg=magenta
```

**Comment by kingmomo** [comment]
Bump for official vim-snazzy

**Comment by sindresorhus** [comment]
@Jarvvski Most terminals today supports 256 or 16million colors, so would be better to use the exact colors in case the user wants a different terminal theme than in VIM.

**Comment by sindresorhus** [comment]
I would be happy to link to a repo if anyone creates this. Won't be done by me as I don't use VIM.

I've done a tweet about it: https://twitter.com/sindresorhus/status/911098992448045056

**Comment by Jarvvski** [comment]
Out of scope for me :)

I would personally not use a different Vim theme to the that of the current terminal

**Comment by danisfermi** [comment]
Bump for an Official vim-snazzy.
