### ISSUE TITLE
iTerm2 version

### ISSUE THREAD

**Issue by Fequois** [sindresorhus/hyper-snazzy#2]
Hey! I just made a version of this delightful colour scheme for iTerm2 in case anyone comes looking for it. It seems to work rather dandy but I haven't tried _everything_ yet.

You may download it [here](https://github.com/sindresorhus/hyperterm-snazzy/files/384573/Snazzy.itermcolors.zip).

![snazzy-iterm](https://cloud.githubusercontent.com/assets/3535255/17151412/6c07c1e2-536b-11e6-8000-2e2db38372d2.png)

**Comment by sindresorhus** [comment]
Cool :) I already have a iTerm2 and Terminal version done locally. Just haven't had the time to publish them yet. I'm planning to create an editor color scheme too.

**Comment by Fequois** [comment]
Aw man, I can only imagine Atom dressed up this beautifully! 😍

And cool, just thought I'd drop this here in case you weren't going to do other versions for others like me who already came looking. 😄

**Comment by sidjain26** [comment]
@sindresorhus any word on the iterm2 version?

**Comment by sindresorhus** [comment]
iTerm2 version is out: https://github.com/sindresorhus/iterm2-snazzy
