### ISSUE TITLE
Pink bottom border on tabs in Hyper ~1.4.0

### ISSUE THREAD

**Issue by ynnoj** [sindresorhus/hyper-snazzy#23]
![screen shot 2017-08-31 at 08 53 48](https://user-images.githubusercontent.com/3578709/29912567-ff822f4e-8e29-11e7-8e7f-873b090e4662.png)

Has become apparent since updating to `1.4.2` this morning. https://github.com/sindresorhus/hyper-snazzy/blob/master/index.js#L63 appears to be the guilty CSS declaration.

**Comment by sindresorhus** [comment]
It's intentional. It was just gone for awhile because of changes in Hyper.

PR welcome for an option to disable it if you don't like it ;)

**Comment by ynnoj** [comment]
@sindresorhus Cool, I'll look at that then 😄
