### ISSUE TITLE
Font isn't rendered as your.

### ISSUE THREAD

**Issue by MarlBurroW** [sindresorhus/hyper-snazzy#35]
Any idea why the text looks so fat on my terminal (it's the same for all fonts).

![image](https://user-images.githubusercontent.com/3024430/33222513-21d34788-d158-11e7-931e-8b1585e6226b.png)

I've inspected the computed css, and the font-weight isn't bold, I don't understand...

I'm on Macosx Sierra.

Thanks for your help

**Comment by sindresorhus** [comment]
Maybe `System Preferences` => `General` and uncheck "Use LCD font smoothing when available".

**Comment by MarlBurroW** [comment]
Nope :(, already checked

**Comment by MarlBurroW** [comment]
Thank you very much ! that's it
