### ISSUE TITLE
Commands not changing colour?

### ISSUE THREAD

**Issue by KingScooty** [sindresorhus/hyper-snazzy#36]
Just installed the latest versions of hyper, zsh, and pure, and the hyper-snazzy theme. Everything seems to be working, but i've noticed the colours of the commands aren't going green.

In the example shot on the pure page, `cd`, `echo` etc go green to show they're commands. Mine seem to stay white.

## Expected

![](https://github.com/sindresorhus/pure/raw/master/screenshot.png)

## Actual

![screen shot 2017-12-15 at 23 28 12](https://user-images.githubusercontent.com/610869/34064282-e4df09ea-e1ef-11e7-8483-4490d3a7965a.png)

Am i missing something?

**Comment by sindresorhus** [comment]
Read the tip in the readme:

> To get the exact same look as in the screenshot, you need to use the Pure prompt, Menlo font, and **the zsh-syntax-highlighting plugin to have commands highlighted.**
