### ISSUE TITLE
Font opacity too dark on Windows 10

### ISSUE THREAD

**Issue by JulienGrv** [sindresorhus/hyper-snazzy#41]
Hi!

I got the same issue with hyper-snazzy as this one here: https://github.com/zeit/hyper/issues/2827

This workaround worked for me: https://github.com/zeit/hyper/issues/2827#issuecomment-382288835

Hope it helps!

**Comment by georgewatts** [comment]
I found the same issue on Mac OS X. The fix was to roll back to version 1.2.2 in the config file as follows:

`plugins: ['hyper-snazzy#1.2.2']`

Although I couldn't see how this problem came about looking at the diffs from the previous commit.

**Comment by Rowno** [comment]
Looks like the latest release broke the inactive pane opacity feature.

**Comment by Rowno** [comment]
Adding this custom css to your config file will override the bug:
```
.terminal, .term_fit:not(.term_term) {
  opacity: 1 !important;
}
```

**Comment by vinkla** [comment]
I'm having this issue as well in the 2.1.0-canary release.

**Comment by senpng** [comment]
![code](https://user-images.githubusercontent.com/7333114/40073136-99a6642a-58a8-11e8-9f10-9368e16b3782.png)
