### ISSUE TITLE
Make Hyper look like screenshot on Windows 10

### ISSUE THREAD

**Issue by ThatWeirdAndrew** [sindresorhus/hyper-snazzy#56]
I'm running Hyper on Windows 10 and I would like to know if it was possible to make it look like the screenshot. I know Windows 10 can't use zsh which is why I'm asking.
Thanks,
Andrew

**Comment by sindresorhus** [comment]
You can use ZSH on Windows with WSL2. I don’t really know any other way. I don’t use Windows.
