### ISSUE TITLE
Atom theme

### ISSUE THREAD

**Issue by tyrollins** [sindresorhus/hyper-snazzy#8]
Would be a brilliant theme for atom editor. 

No clue how to create themes, so unfortunately all I can do is suggest...

**Comment by sindresorhus** [comment]
Yes, I'm already working on that.

**Comment by pveyes** [comment]
Hi, thanks @sindresorhus for this. I built a syntax theme (not full fledge UI theme) based on this theme.

If anyone interested https://github.com/pveyes/atom-snazzy-clear-syntax. I'm currently using it with Atom Material UI theme.

**Comment by sindresorhus** [comment]
Closing as Atom is being shut down: https://github.blog/2022-06-08-sunsetting-atom/
